### ISSUE TITLE
Remove the old embodiment

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1766]
# Overview

The old embodiment is being replaced with a better infrastructure. A
lot of components are no longer being useful, such as the
perception/action interface, the world wrapper, etc. This issue aims
at listing the components to remove and explain why they should
be. I'll edit that issue as the discussion evolves.

# Components to remove

Here's a table showing the components to be removed, the pros (for
removal) and cons (against removal).

```table
+----------------------------+------------------------------+--------------------+-+
|Component to remove         |Pros                          |Cons                |D|
|(sub-directory of           |                              |                    |e|
|opencog/embodiment)         |                              |                    |l|
+----------------------------+------------------------------+--------------------+-+
|AtomSpaceExtensions         |Probably only used by the old |Some atom types are |X|
|                            |OpenPsi.                      |used by the new     | |
|                            |                              |OpenPsi (rightly or | |
|                            |                              |not), so the atom   | |
|                            |                              |types definitions   | |
|                            |                              |have been kept.     | |
+----------------------------+------------------------------+--------------------+-+
|AutomatedSystemTest         |Nobody has used this tool     |                    |X|
|                            |(pbTest) for years and it     |                    | |
|                            |crashes.                      |                    | |
+----------------------------+------------------------------+--------------------+-+
|AvatarComboVocabulary       |Unlikely to be used by the new|Complex example of  |X|
|                            |embodiment.                   |action/perception   | |
|                            +------------------------------+combo vocabulary    | |
|                            |The ant combo vocabulary can  |definition.         | |
|                            |serve as example as well.     |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control/Language            |I'm assuming this isn't used  |                    |X|
|                            |anywhere. Last commits on this|                    | |
|                            |were from Linas in April 2015,|                    | |
|                            |apparently as a consequence of|                    | |
|                            |other changes.                |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control/MessagingSystem     |I don't think this would be   |                    |X|
|                            |used anymore. If the OAC and  |                    | |
|                            |the learning server are being |                    | |
|                            |removed, we can probably      |                    | |
|                            |remove that.                  |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control                     |We probably want to remove it |                    |X|
|/OperationalAvatarController|entirely, although I'm not    |                    | |
|                            |100% sure. It depends on how  |                    | |
|                            |the new embodiment loop has   |                    | |
|                            |been implemented so far. I    |                    | |
|                            |have no knowledge about that. |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control                     |Ben thinks we should remove   |                    |X|
|/OperationalAvatarController|the OCPlanner and re-implement|                    | |
|/OCPlanner                  |it using the URE.             |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control                     |Should be replaced by new     |                    |X|
|/PerceptionActionInterface  |embodiment code (behavior     |                    | |
|                            |trees and grounded            |                    | |
|                            |schema/predicate nodes). Linas|                    | |
|                            |and others may comment on     |                    | |
|                            |that.                         |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control/PredicateUpdaters   |Replaced by new embodiment    |                    |X|
|                            |code (grounded predicate      |                    | |
|                            |nodes, etc). Linas and others |                    | |
|                            |may comment on that.          |                    | |
+----------------------------+------------------------------+--------------------+-+
|Control/Procedure           |Replaced by the execution     |                    |X|
|                            |module.                       |                    | |
+----------------------------+------------------------------+--------------------+-+
|Learning                    |This code doesn't run anymore |Perhaps the         |X|
|                            |and is overfit to imitation   |learning server can | |
|                            |learning. Ideas can be stolen |be reused. I don't  | |
|                            |but not code.                 |think so but I'm    | |
|                            |                              |not 100% sure.      | |
+----------------------------+------------------------------+--------------------+-+
|Monitor                     |I believe this was created for|                    |X|
|                            |the old OpenPsi. I don't know |                    | |
|                            |how useful that code may      |                    | |
|                            |be. Can someone comment on    |                    | |
|                            |this (AmeBel?).               |                    | |
+----------------------------+------------------------------+--------------------+-+
|WorldWrapper                |Replaced by the execution     |It could be that    |X|
|                            |module. Once I'm done with it |WorldWrapperUtil is | |
|                            |I'll clean the old combo      |still used by other | |
|                            |interpreter as well.          |components. Methods | |
|                            |                              |may be moved        | |
|                            |                              |elsewhere, if       | |
|                            |                              |necessary.          | |
+----------------------------+------------------------------+--------------------+-+
```

Of course there's other related things to remove such that the
corresponding unit tests and scripts

# Corresponding replacements

Here's a table relating the to-be-removed components (indicated by
their subdirectories in opencog/embodiment) to their current or future
substitutes.

```table
+--------------------------------------+----------------------------------------+
|To-be-removed component (sub-directory|Subtitute                               |
|of opencog/embodiment)                |                                        |
+--------------------------------------+----------------------------------------+
|AutomatedSystemTest                   |?                                       |
+--------------------------------------+----------------------------------------+
|AvatarComboVocabulary                 |?                                       |
+--------------------------------------+----------------------------------------+
|Control/Language                      |?                                       |
+--------------------------------------+----------------------------------------+
|Control/MessagingSystem               |?                                       |
+--------------------------------------+----------------------------------------+
|Control/OperationalAvatarController   |?                                       |
+--------------------------------------+----------------------------------------+
|Control/OperationalAvatarController   |?                                       |
|/OCPlanner                            |                                        |
+--------------------------------------+----------------------------------------+
|Control/PerceptionActionInterface     |?                                       |
+--------------------------------------+----------------------------------------+
|Control/PredicateUpdaters             |?                                       |
+--------------------------------------+----------------------------------------+
|Control/Procedure                     |AtomSpace's execution module            |
|                                      |(i.e. opencog/atoms/execution in the    |
|                                      |atomspace repo).                        |
+--------------------------------------+----------------------------------------+
|Learning                              |TBD                                     |
+--------------------------------------+----------------------------------------+
|Monitor                               |?                                       |
+--------------------------------------+----------------------------------------+
|WorldWrapper                          |AtomSpace's execution module            |
+--------------------------------------+----------------------------------------+
```

# Sub-tasks

- [X] Create a tag for the old embodiment, before removal. I assume I
  don't need to tag the OCPlanner separately for instance, just one tag
  for the whole old embodiment is enough.

- [X] Remove components by components, each commit corresponding to
  one components + its associated unit tests and scripts. Starting
  from the most most obvious and peripheral ones, like the Learning,
  WorldWrapper, etc, to the least obvious and core ones, like the
  MessagingSystem. Here's a temptative list, to be revisited as we
  proceed. List of components to remove:
  - [X] Learning
  - [X] AutomatedSystemTest
  - [X] Control & WorldWrapper (highly coupled)
  - [X] AvatarComboVocabulary
  - [X] AtomSpaceExtensions
    - [X] AtomSpaceExtensions C++ code
    - [X] atom types (old atom types like PetNode seems still used in
      the new OpenPsi, I decided to keep everything for now)
  - [X] Monitor
  - [X] Embodiment scripts

# Concluding remarks

Likely bad surprises will arise, like forgotten dependencies. We'll
figure out how to deal with them as they unfold.

**Comment by ngeiswei** [comment]
Arrrggg, github/markdown doesn't understand that table format, let me try to fix that...

**Comment by ngeiswei** [comment]
I'll keep the code block trick for the table (that at least emacs understands). You may feel free to edit the top message and fill the blanks to the best of your knowledge. Or provide your feedback in subsequent message. Thanks.

**Comment by ngeiswei** [comment]
I've created a tag for the old embodiment https://github.com/opencog/opencog/releases/tag/old-embodiment_8-nov-2015 (first git tag ever, critical feedback welcome if needed).

**Comment by pennachin** [comment]
Looks like GitHub treats all tags as releases (or potential releases, according to help and stackoverflow), so I've marked your tag as not-production to hopefully reduce confusion.

**Comment by ngeiswei** [comment]
I've just realized the OperationalAvatarController has been disabled by Amen 2 months ago. This comforts my though that we want the OAC gone.

**Comment by ngeiswei** [comment]
As a result I decided to take a bold move and remove embodiment/Control entirely, meaning
```
Control/Language
Control/MessagingSystem
Control/OAC
Control/OCPlanner
Control/PAI
Control/Procedure
```
I'm assuming it's fine. Let me know if I need to resurrect one of them.

**Comment by ngeiswei** [comment]
I'm on my way to conclude that, I need the feedback for 2 things

1. NLP file under opencog/embodiment
```
framesInheritance.list
frames.list
frames2relex.rules
dialog_system.scm
```
2. Is the opencog/embodiment/Monitor component obsolete?

In the absence of feedback within the next couple of hours I'll remove them (from the feature branch of course, not the master).

**Comment by bgoertzel** [comment]
frame2relex is cool but long-deprecated, along with relex2frame

I *believe* dialog_system.scm is something old that Zhenhua wrote, which is not currently needed, as we have a new and shinier dialog system architecture now...

opencog/embodiment/Monitor  -- well I would suppose this would need some changes to work with the new OpenPsi that Amen has built, i.e. it won't run except in the context of the old OpenPsi that we're not going to use anymore... So I guess it's OK to remove it so long as it's properly tagged.  The functionality that it carries out is a useful one, though probably when we reimplement the functionality we will want to do it integrated w/ the Atomspace viewer, not using these separate tools anyway...

**Comment by ngeiswei** [comment]
Thanks, Ben. The tag is just the same one for the whole embodiment code, but I've added a word about the potentially reusable components in the tag's comment.

**Comment by linas** [comment]
we can close this, right?
